use_frameworks!

platform :ios, '9.0'

target 'ChatBotDino_Example' do
  pod 'ChatBotDino', :path => '../'

  target 'ChatBotDino_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
